stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - src/prepare.py
    params:
    - prepare.categories
    outs:
    - data/prepared
  featurize:
    cmd: python src/featurize.py data/prepared data/features
    deps:
    - data/prepared
    - src/featurize.py
    outs:
    - data/features
